"""Phase 4-11 full architectural schema

Revision ID: 6de6cb1633a8
Revises: c8138788456a
Create Date: 2026-09-30 18:21:34.214336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de6cb1633a8'
down_revision: Union[str, Sequence[str], None] = 'c8138788456a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
