"""add_indexes_to_fks_and_rls_policies

Revision ID: 97b5e501f351
Revises: aef1a14e5810
Create Date: 2026-10-06 22:09:22.716680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b5e501f351'
down_revision: Union[str, Sequence[str], None] = 'aef1a14e5810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assignments_division_id'), 'assignments', ['division_id'], unique=False)
    op.create_index(op.f('ix_assignments_subject_id'), 'assignments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_assignments_teacher_id'), 'assignments', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_class_session_id'), 'attendance_sessions', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_batches_course_id'), 'batches', ['course_id'], unique=False)
    op.create_index(op.f('ix_bookings_resource_id'), 'bookings', ['resource_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_division_id'), 'class_sessions', ['division_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_subject_id'), 'class_sessions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_teacher_id'), 'class_sessions', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_courses_department_id'), 'courses', ['department_id'], unique=False)
    op.create_index(op.f('ix_divisions_batch_id'), 'divisions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_enrollments_division_id'), 'enrollments', ['division_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_event_id'), 'event_registrations', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_student_id'), 'event_registrations', ['student_id'], unique=False)
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_exam_marks_exam_id'), 'exam_marks', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_marks_student_id'), 'exam_marks', ['student_id'], unique=False)
    op.create_index(op.f('ix_exams_division_id'), 'exams', ['division_id'], unique=False)
    op.create_index(op.f('ix_exams_subject_id'), 'exams', ['subject_id'], unique=False)
    op.create_index(op.f('ix_notices_author_id'), 'notices', ['author_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_staff_profiles_department_id'), 'staff_profiles', ['department_id'], unique=False)
    op.create_index(op.f('ix_staff_profiles_user_id'), 'staff_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_student_profiles_batch_id'), 'student_profiles', ['batch_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_department_id'), 'student_profiles', ['department_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_subjects_course_id'), 'subjects', ['course_id'], unique=False)
    op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    # ### end Alembic commands ###

    conn = op.get_bind()
    if conn.dialect.name == 'postgresql':
        op.execute('CREATE POLICY "deny_all" ON public."departments" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."courses" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."events" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."users" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."resources" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."bookings" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."notices" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."notifications" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."class_sessions" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."audit_logs" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."assignments" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."subjects" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."event_registrations" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."attendance_sessions" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."exams" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."submissions" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."exam_marks" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."attendance_records" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."staff_profiles" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."batches" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."student_profiles" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."divisions" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."enrollments" FOR ALL USING (false);')
        op.execute('CREATE POLICY "deny_all" ON public."alembic_version" FOR ALL USING (false);')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    op.drop_index(op.f('ix_subjects_course_id'), table_name='subjects')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_department_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_batch_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_staff_profiles_user_id'), table_name='staff_profiles')
    op.drop_index(op.f('ix_staff_profiles_department_id'), table_name='staff_profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notices_author_id'), table_name='notices')
    op.drop_index(op.f('ix_exams_subject_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_division_id'), table_name='exams')
    op.drop_index(op.f('ix_exam_marks_student_id'), table_name='exam_marks')
    op.drop_index(op.f('ix_exam_marks_exam_id'), table_name='exam_marks')
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.drop_index(op.f('ix_event_registrations_student_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_event_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_division_id'), table_name='enrollments')
    op.drop_index(op.f('ix_divisions_batch_id'), table_name='divisions')
    op.drop_index(op.f('ix_courses_department_id'), table_name='courses')
    op.drop_index(op.f('ix_class_sessions_teacher_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_subject_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_division_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_resource_id'), table_name='bookings')
    op.drop_index(op.f('ix_batches_course_id'), table_name='batches')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_attendance_sessions_class_session_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_assignments_teacher_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_subject_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_division_id'), table_name='assignments')
    # ### end Alembic commands ###

    conn = op.get_bind()
    if conn.dialect.name == 'postgresql':
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."departments";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."courses";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."events";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."users";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."resources";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."bookings";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."notices";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."notifications";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."class_sessions";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."audit_logs";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."assignments";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."subjects";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."event_registrations";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."attendance_sessions";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."exams";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."submissions";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."exam_marks";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."attendance_records";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."staff_profiles";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."batches";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."student_profiles";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."divisions";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."enrollments";')
        op.execute('DROP POLICY IF EXISTS "deny_all" ON public."alembic_version";')

