"""Phase 3 and 4 QR expiration and uniqueness

Revision ID: f95a4c1d4dbd
Revises: 6de6cb1633a8
Create Date: 2026-09-30 19:30:06.856389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95a4c1d4dbd'
down_revision: Union[str, Sequence[str], None] = '6de6cb1633a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_session_student', ['session_id', 'student_id'])

    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_column('closed_at')
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_constraint('uix_session_student', type_='unique')
    # ### end Alembic commands ###
